const swaggerAutogen = require('swagger-autogen')()


const doc = {
    info: {
        version: "1.0.0",
        title: "IntelliaTech Portal API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "employee-portal-backend-node.herokuapp.com/",
    basePath: "/",
    schemes: ['https', 'http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {
        Bearer: {
          type: "apiKey",
          name: "Authorization",
          in: "header"
         }
      },
    definitions: {
        Parents: {
            father: "Simon Doe",
            mother: "Marie Doe"
        },
        User: {
            name: "Jhon Doe",
            age: 29,
            parents: {
                $ref: '#/definitions/Parents'
            },
            diplomas: [
                {
                    school: "XYZ University",
                    year: 2020,
                    completed: true,
                    internship: {
                        hours: 290,
                        location: "XYZ Company"
                    }
                }
            ]
        },
        AddUser: {
            $name: "Jhon Doe",
            $age: 29,
            about: ""
        }
    }
}

const outputFile = './swagger_output.json'
const endpointsFiles = ['./express.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./express')           // Your project's root file
})


// swagger demo code 

// "User": {
//     "type": "object",
//     "properties": {
//       "name": {
//         "type": "string",
//         "example": "Jhon Doe"
//       },
//       "age": {
//         "type": "number",
//         "example": 29
//       },
//       "parents": {
//         "$ref": "#/definitions/Parents"
//       },
//       "diplomas": {
//         "type": "array",
//         "items": {
//           "type": "object",
//           "properties": {
//             "school": {
//               "type": "string",
//               "example": "XYZ University"
//             },
//             "year": {
//               "type": "number",
//               "example": 2020
//             },
//             "completed": {
//               "type": "boolean",
//               "example": true
//             },
//             "internship": {
//               "type": "object",
//               "properties": {
//                 "hours": {
//                   "type": "number",
//                   "example": 290
//                 },
//                 "location": {
//                   "type": "string",
//                   "example": "XYZ Company"
//                 }
//               }
//             }
//           }
//         }
//       }
//     }
//   },
//   "AddUser": {
//     "type": "object",
//     "properties": {
//       "name": {
//         "type": "string",
//         "example": "Jhon Doe"
//       },
//       "age": {
//         "type": "number",
//         "example": 29
//       },
//       "about": {
//         "type": "string",
//         "example": ""
//       }
//     },
//     "required": [
//       "name",
//       "age"
//     ]
//   },


// "/v2/test-get": {
//     "get": {
//       "tags": [],
//       "description": "Description here...",
//       "parameters": [],
//       "responses": {
//         "200": {
//           "description": "OK"
//         },
//         "401": {
//           "description": "Unauthorized"
//         }
//       }
//     }
//   },
//   "/v2/test-delete/{id}": {
//     "delete": {
//       "tags": [],
//       "description": "",
//       "parameters": [
//         {
//           "name": "id",
//           "in": "path",
//           "required": true,
//           "type": "string"
//         }
//       ],
//       "responses": {
//         "200": {
//           "description": "OK"
//         },
//         "401": {
//           "description": "Unauthorized"
//         }
//       }
//     }
//   }


// "/test-get": {
//     "get": {
//       "tags": [],
//       "description": "",
//       "produces": [
//         "application/json"
//       ],
//       "parameters": [],
//       "responses": {
//         "200": {
//           "description": "OK"
//         }
//       }
//     }
//   },
//   "/test-post": {
//     "post": {
//       "tags": [],
//       "description": "",
//       "parameters": [],
//       "responses": {
//         "201": {
//           "description": "Created"
//         }
//       }
//     }
//   },
//   "/test-delete/{id}": {
//     "delete": {
//       "tags": [],
//       "description": "",
//       "parameters": [
//         {
//           "name": "id",
//           "in": "path",
//           "required": true,
//           "type": "string"
//         }
//       ],
//       "responses": {
//         "204": {
//           "description": "No Content"
//         }
//       }
//     }
//   },